### ISSUE TITLE
cabinet model and flooring shape & textures

### ISSUE THREAD

**Issue by CGARCHITECT** [CreativeDesigner3D/PyClone#1]
Hi CreativeDesigner3D/PyClone,

![Screenshot 2020-11-13 193752](https://user-images.githubusercontent.com/74409665/99068587-c0f6b980-25e7-11eb-90d7-a2d59cd817ee.jpg)

Thank you for your startup, looking forward to these amazing tools for interior visualization. 

I am having problems with floor textures and doors and cabinets, they are appearing wireframe in the model and rendered mode

Thank you.

**Comment by CreativeDesigner3D** [comment]
I haven't seen this happen before. Go to Window > Toggle System Console and see if you are getting any errors.

**Comment by Kimerabubble** [comment]
I had the same issue after the activation of add-ons so i went in directory, add "everyone" user to let all permissions, reopen blender pyclone and voilà, not more issue :smiley: 

This tools is very amazing!
