### ISSUE TITLE
Arch Linux build

### ISSUE THREAD

**Issue by Sinasta** [CreativeDesigner3D/PyClone#10]
Hello there, i would like to ask if someone managed to make a PyClone Build for linux? Is there someone willing to make a version for Arch linux (Manjaro).
I would love to test this great Addon
Thank you

**Comment by matheusfillipe** [comment]
I guess this add on will only work on his custom blender build: https://github.com/CreativeDesigner3D/BlenderSource
Haven't found anyone that build that for linux so far but I've been trying to build it, but had an issue right on the end: https://github.com/CreativeDesigner3D/BlenderSource/issues/4

If I am able to I will add the pyclone-bin package to AUR... Or would be happy if anyone else figures this out as well.

**Comment by zauberparacelsus** [comment]
I've created a `blender-pyclone-git` PKGBUILD, though have not yet uploaded it.  I'm having a little problem with the library addons not working due to #16

**Comment by BlueMax** [comment]
Is it still useful now that PyClone is compatible with default Blender? Just for the drag&drop feature?

**Comment by matheusfillipe** [comment]
No that is no longer needed even though I wasn't able to use it yet

![image](https://user-images.githubusercontent.com/24435787/103047533-93981680-456a-11eb-8fe2-c555e07042a9.png)

**Comment by matheusfillipe** [comment]
Never mind just needed to restart and install again now it works!

**Comment by BlueMax** [comment]
You're probably on Windows. I get the same error in #14. The function 'getchildren' is actually deprecated and no longer available in Python v3.9.1. Blender ships with an own Python version and might override the system-wide Python installation.

**Comment by matheusfillipe** [comment]
No, I am on arch linux. But it worked now, I needed to uninstall, install again and restart blender.

**Comment by BlueMax** [comment]
Which Python version are you running?
```
$ python -V
Python 3.9.1
```

**Comment by matheusfillipe** [comment]
@BlueMax, I have python 3.9.1 as well. I don't know why that should matter anyway, the OS python never affects the blender python, blender has it's own python bundled in. This means blender is not reading my /usr/lib/site-packages, you can check in blender shell is a different version (3.7.4 for blender 2.9.0).

**Comment by BlueMax** [comment]
You're on an outdated arch system. Neither Blender 2.9.0 is actual (its 2.9.1) nor is there any Python bundled within Blender in Arch (see [here](https://archlinux.org/packages/community/x86_64/blender/), list files below). Also see external dependenciy `'python'` that is 3.9.1.
The blender console (`blender --python-console`) shows 3.9.1 here as well.

**Comment by matheusfillipe** [comment]
I am not using the blender from arch repos, that is why.

**Comment by zauberparacelsus** [comment]
I've reinstalled Arch's blender, and then installed the Pyclone and the Home Builder addons.  However, when I try to drag and drop anything from the home builder into a blender scene, it just drops an empty with the item's image into the scene, and doesn't do anything else.  Right-clicking on these does nothing as well.

**Comment by BlueMax** [comment]
Forget Arch's Blender. Its useless. The Python versions differ too much to do "dirty hacks" to downgrade. At least i couldn't find a solution. Other addons like OpenBIM don't work properly either.
