### ISSUE TITLE
Error (I ran it as administrator.. still doesn't work)

### ISSUE THREAD

**Issue by BATTERYexe** [CreativeDesigner3D/PyClone#11]
![image](https://user-images.githubusercontent.com/64132810/100227721-db069500-2f21-11eb-91bb-ba8bb058b3bd.png)
(I ran it as administrator.. still doesn't work)

**Comment by CreativeDesigner3D** [comment]
I have made some updates to fix these types of issues. Try the latest version and let me know if you are still running into issues.
