### ISSUE TITLE
Only opens one object whereas I have two linked curves

### ISSUE THREAD

**Issue by fd3dprinting** [CreativeDesigner3D/PyClone#15]
Hi Andrew – I have setup Blender 2.91 with your Dec. 2020 addon PyClone with the Toy Box Library and I am using the P key to add the assets. I have loads of assets that used to work with FluidDesigner and now also work with the JewelCraft addon but only half of them work with your new system. The problem is that most of my assets have two objects, basically two inter-linked Curves rather than a single Mesh object. One of the Curve objects is basically the Bevel Object and the other is the required finished object (the finished object is that which displayed in the .png icon). Your setup seems to only open one object and if it opens the Curve that is the Bevel Object it is basically useless because it doesn’t also open the other Curve. When it opens the required Curve, i.e. the one that should be the finished object that is displayed in the .png icon, it works albeit it does not put the Bevel Object in the Outline window, but I can live with that. If you download the Dropbox link shown below there are two asset folders “Patterns Alchemy” and “Patterns Alphabet Anglo Saxon Runes”. Alchemy doesn’t work but Saxon Runes do. If there is a simple fix it would be great if you could do it. PyClone looks great.
Paul Summers
DropBox Link – click on the download arrow (top right) and then Direct Download
https://www.dropbox.com/s/fe2g2m2tvxadddf/fluiddesigner-andrew.zip?dl=0

**Comment by CreativeDesigner3D** [comment]
I believe I have this fixed. let me know if you are still running into issues with the latest release.
