### ISSUE TITLE
feature request: integration Asset manager

### ISSUE THREAD

**Issue by Sinasta** [CreativeDesigner3D/PyClone#18]
Hello there. Thanks a lot for your great work! I wanted to ask if the're any plans on an integration into blenders native asset manager? As of today pyclone breaks the asset manager.

**Comment by CreativeDesigner3D** [comment]
Yeah I will integrate it with Blenders native asset system, but since 2.93 is in alpha I am waiting for blenders core team to finish development before I being the implementation.

**Comment by Sinasta** [comment]
Great thank you!
