### ISSUE TITLE
pyclone 

### ISSUE THREAD

**Issue by Marlimcps** [CreativeDesigner3D/PyClone#2]
i have this after installing the program. What am i doing wrong? Library is empty. Thanks in advance .

https://gyazo.com/3a9e102bb69fd6e22a0dbb4edb551407

**Comment by CreativeDesigner3D** [comment]
Go to Window > Toggle System Console and see if you are getting any errors.

**Comment by Marlimcps** [comment]
i got this after  doing what you said ( and thank you for fast asnwer, sorry delay from my side)

https://gyazo.com/004789e8cd403c1ae51e44c85252a2f4

**Comment by Marlimcps** [comment]
oops sorry my bad...i reinstaled blender again and still didnt set the add on again...ill send you  answer later

**Comment by Marlimcps** [comment]
sorry sir, for the last post...  i was using blender 2.91 and forgot i had deleted the version 2.90. Its all working now:) I wish to thank you very much for the fast answer and for the program. Its just marvelous, you did a great and hard job there! thank you.
