### ISSUE TITLE
PyClone breaks the Assets Browser Header menu in Blender 3.4.1

### ISSUE THREAD

**Issue by marcelhoogantink** [CreativeDesigner3D/PyClone#26]
Hi,

Trying your fine PyClone add-on, I found that the install of this add-on breaks the header options of the asset-browser in 3.4.1:

Original:
![original header](https://user-images.githubusercontent.com/51886888/222737587-c0f750a2-436d-45fb-9a9f-15d2c065f1f1.PNG)

After PyClone ad-on install:

![afbeelding](https://user-images.githubusercontent.com/51886888/222736447-71b509f5-89c7-4067-9002-bdb1ea6942fe.png)

Several options in the header are gone: the edit option and all other options at the right side of it are gone.

Do you know a way to get them back. I used to use the import-type (append / link) often...

**Comment by CreativeDesigner3D** [comment]
I just released a video that explains the new version that is compatible with Blender 3.4

https://youtu.be/hzdL8Wks45A
