### ISSUE TITLE
Can I add this to my own build?

### ISSUE THREAD

**Issue by juangea** [CreativeDesigner3D/PyClone#3]
This is the question :) 

Can I add this to my own build?
¿Is it maintained and compatible with master?

It seems very interesting :)

**Comment by CreativeDesigner3D** [comment]
Yeah it is built off of Blender 2.90 release. 

You can find my changes to blenders source in this repo

https://github.com/CreativeDesigner3D/BlenderSource

Give it a try and let me know if you run into any issues.
