### ISSUE TITLE
Visible issue for remove Range hood of Range

### ISSUE THREAD

**Issue by Kimerabubble** [CreativeDesigner3D/PyClone#4]
### Steps to make the issue (deleting):
If i open the **Range prompts** and uncheck **Add range hood**, result: the range hood still appears.
**Workaround**: you can delete it manually but the flag **Add range hood** remains enabled, is normal?

Thank you for your support!

**Comment by adaelvira** [comment]
> If i open the **Range prompts** and uncheck **Add range hood**, result: the range hood still appears.
> **Workaround**: you can delete it manually but the flag **Add range hood** remains enabled, is normal?
>
hello, I have the opposite issue.
I mean:

If i open the **Range prompts** the flag **Add range hood** is disabled.
Then I check **Add range hood**, result: the range hood (only one seems available) doesn't appear, the flag **Add range hood** remains disabled

thank you and regards

**Comment by Kimerabubble** [comment]
> Then I check Add range hood, result: the range hood (only one seems available) doesn't appear,

Hi @adaelvira , it's a misunderstanding. Initially I got the same wrong thought about it.
If you see the the way the preview video shows how to use Home builder you can see that you have not only check the flag but you also have to click on the image of range hood and than chose with a click on thumbnail of the rang hood you want (only one for now).
I wrote the same issue but i corrected it leaving only, i think, tha right issue.

I hope you understood me :-)

I suggest you to see the video introduction.

Bye!
