### ISSUE TITLE
Alignment not correct on create/selecting thumbnail of Dishwasher?

### ISSUE THREAD

**Issue by Kimerabubble** [CreativeDesigner3D/PyClone#5]
Hi Andrew, an other little issue:

If you create a dishwasher from draging and click on viewport, the table top will be on the base with a little gap of space from it. If you open promps command and, after click on image of dishwasher, you select the thumbnail of it, the table top will be re-aligned instantly on base without gap.

If i add other cabinets next to it i notice that the first gap is "correct" because the table top is at the same height (or Z origin) of table top of the cabinets but whitout the gap, the height of the table top is more lower than the table top of cabinets.

Is an issue about the initial height of the base of the dishwasher (that cause the gap)?

Thank you!

**Comment by CreativeDesigner3D** [comment]
This should be fixed in the latest release. let me know if you are still running into issues.
