### ISSUE TITLE
I have an issue

### ISSUE THREAD

**Issue by JJRays** [CreativeDesigner3D/PyClone#7]
![image](https://user-images.githubusercontent.com/74538354/99241727-887cf880-27fe-11eb-9287-a3f69a592edf.png)
Look at the image
It showed me that error message when I tried to enable home builder
and I followed the instrucyions You gave here:
https://creativedesigner3d.com/2020/11/12/installing-blender-with-pyclone-2-90/

**Comment by JJRays** [comment]
Do you have to have the original blender or just the pyclone

**Comment by JJRays** [comment]
Oh wait I figured it out myself. Thanks for the awesome addon any way

**Comment by curraheestephen** [comment]
> Oh wait I figured it out myself. Thanks for the awesome addon any way

Hello,
I also have the same issue, how did you figure it out? Kindly help, thanks!

**Comment by IvailoBurov** [comment]
The same issue here.

**Comment by zaefyra** [comment]
I had this issue. I restarted blender with administrator control and it worked.
